apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: amqs-cluster
  namespace: amq-demo
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 1
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - name: route
        port: 9094
        tls: true
        type: route
    replicas: 3
    storage:
      class: ocs-storagecluster-ceph-rbd
      deleteClaim: false
      size: 3Gi
      type: persistent-claim
  zookeeper:
    replicas: 3
    storage:
      class: ocs-storagecluster-ceph-rbd
      deleteClaim: false
      size: 1Gi
      type: persistent-claim

---

apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: workshop
  namespace: amq-demo
  labels:
    strimzi.io/cluster: amqs-cluster
spec:
  config:
    retention.ms: 604800000 #7 güne denk geliyor
    segment.bytes: 1073741824
  partitions: 3
  replicas: 3
  topicName: workshop-log-topic

##bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic workshop-log-topic --from-beginning

# bin/kafka-topics.sh --create --topic merhaba --bootstrap-server localhost:9092 

# bin/kafka-topics.sh --describe --topic merhaba --bootstrap-server localhost:9092

#172.30.61.183:2181

