namespace: reverse-words-production
commonLabels:
  app: reversewords-prod
bases:
- github.com/AltugYildirim/GitOps-Advanced/?ref=config
resources:
- namespace.yaml
- route.yaml
patchesStrategicMerge:
- deployment.yaml
