namespace: reverse-words-stage
commonLabels:
  app: reversewords-stage
bases:
- github.com/AltugYildirim/GitOps-Advanced?ref=main
resources:
- namespace.yaml
- ingress.yaml
patchesStrategicMerge:
- deployment.yaml